- type: job
  id: MedicalDoctor
  name: job-name-doctor
  altNames:
    - job-name-doctor-alt
    - job-name-doctor-alt2
    - job-name-doctor-alt3
  description: job-description-doctor
  playTimeTracker: JobMedicalDoctor
  startingGear: DoctorGear
  icon: "MedicalDoctor"
  supervisors: job-supervisors-cmo
  access:
  - Medical
  - Chemistry
  - Maintenance
  special:
  - !type:AddComponentSpecial
    components:
    - type: MedicalTraining

- type: startingGear
  id: DoctorGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitMedicalDoctor
    back: ClothingBackpackMedicalFilled
    shoes: ClothingShoesColorWhite
    # outerClothing: ClothingOuterCoatLab
    id: MedicalPDA
    # neck: ClothingNeckStethoscope
    ears: ClothingHeadsetMedical
    belt: ClothingBeltMedicalFilled
  innerclothingskirt: ClothingUniformJumpskirtMedicalDoctor
  satchel: ClothingBackpackSatchelMedicalFilled
  duffelbag: ClothingBackpackDuffelMedicalFilled
